version: '3.9'

services:
  backend:
    build: 
      context: ../../
      dockerfile: docker/staging/Dockerfile
    ports:
      - 9000:8000
    volumes:
      - ../../:/app
    command: uvicorn batikpedia.asgi:application --host 0.0.0.0 --port 8000 --reload --log-level=debug
    environment:
      - DEBUG=1