name: Deploy to Cloud Run

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CLOUD_RUN_SERVICE_ACCOUNT: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
  REGION: asia-southeast2
  SERVICE: batikpedia-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Build and deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}
          credentials: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
          build-push: true