name: Deploy to Cloud Run

on:
  push:
    branches: [staging]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CLOUD_RUN_SERVICE_ACCOUNT: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
  REGION: asia-southeast2
  SERVICE: batikpedia-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: google-github-actions/auth@v2
        with:
          service_account: ${{ env.CLOUD_RUN_SERVICE_ACCOUNT }}
      
      - name: Inject service account credentials
        uses: google-github-actions/inject-secret@v2
        with:
          name: CLOUD_RUN_SERVICE_ACCOUNT
          path: .
      
      - name: Build Docker image
        uses: docker/build@v3
        with:
          dockerfile: Dockerfile
          push: true
      
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest
          region: ${{ env.REGION }}